### ISSUE TITLE
Consolidate tabs vs spaces in the code

### ISSUE THREAD

**Issue by icnocop** [SpecBind/specbind#168]
Hi.

I'd like to consolidate tabs vs. spaces in the code so they're consistent.

It'll make the code more easier to maintain when comparing pull requests for example.

It seems we can use stylecop's `useTabs` setting.

What do you think?

Thank you.

**Comment by dpiessens** [comment]
Has this really been an issue with reviewing PRs? GitHub is pretty good at ignoring white space differences, and enforcing it is one of those "holy wars" I'd like to avoid.

Sure, I've used ReSharper exclusively over the years so I thought the code was pretty consistent overall. I never checked PRs that closely though and I personally like alignment over just tabs so I'll mix. 

If you have a tool that can make the code base consistent I'd be interesting in seeing how drastic the change is.

**Comment by icnocop** [comment]
I've seen some misalignment in the code.

Here's just one example:
https://github.com/dpiessens/specbind/blob/master/src/SpecBind/PageNavigationSteps.cs#L28

Here's an example of misalignment in a PR:
https://github.com/dpiessens/specbind/pull/151/files#diff-2aad4c3d2898d7f55d27fedfe457c66dR17

One solution could be to use EditorConfig, although I haven't personally used it (yet):
https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2017#example

Here's a Visual Studio extension that can automatically format all files in a solution:
https://marketplace.visualstudio.com/items?itemName=munyabe.FormatAllFiles

Thank you.

**Comment by icnocop** [comment]
I added .editorconfig in PR #201 
To apply the format on all files in the solution run `dotnet format src\SpecBind.sln`
https://github.com/dotnet/format/
