### ISSUE TITLE
"I am on list (.+) item ([0-9]+)" and "I am on (.+) list item matching criteria" selection steps are not documented

### ISSUE THREAD

**Issue by icnocop** [SpecBind/specbind#193]
Hi.

I noticed the following step bindings are not documented:

- "I am on list (.+) item ([0-9]+)"

- "I am on (.+) list item matching criteria"

I expected it to be documented in https://github.com/dpiessens/specbind/wiki/Verifying-Steps for example.

Thank you.

**Comment by dpiessens** [comment]
This is actually documented under Navigating Steps -> Selecting Items in a List
